{{- if include "gpg.shouldGenerateKeys" . }}
{{- if (index .Values "gpg").serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpg.serviceAccountName" . }}
  labels:
    {{- include "gpg.labels" . | nindent 4 }}
  {{- with (index .Values "gpg").serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ (index .Values "gpg").serviceAccount.automount }}
{{- end }}
{{- end }}