{{- $keycloak_repo_base := "" -}}
{{- if ((include "testValuesPath" (list .Values "global" "image" "repo" "base")) | eq "true") }}
  {{/* Keycloak image if mirrored repository is used*/}}
  {{- $keycloak_repo_base = .Values.global.image.repo.base | default .Values.image.keycloak.repo.base }}
{{- else }}
  {{/* Keycloak image if mirrored repository is not used*/}}
  {{- $keycloak_repo_base = .Values.image.keycloak.repo.base }}
{{ end -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keycloak.fullname" . }}-realm-update
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  template:
    spec:
      containers:
        - name: update-realm
          image: "{{ $keycloak_repo_base }}/{{ .Values.image.keycloak.repo.path }}:{{ .Values.image.keycloak.tag }}"
          imagePullPolicy: {{ .Values.image.kubectl.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "keycloak.fullname" . }}-realm-update-env
                optional: false
          env:
            - name: KCADM_CFG_PATH
              value: "/workdir/kcadm.config"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 50m
              memory: 128Mi
          command:
            - "/updates/apply.sh"
          volumeMounts:
            - mountPath: /admin
              name: admin-credentials
              readOnly: true
            - mountPath: /updates
              name: realm-update-scripts
            - mountPath: /workdir
              name: workdir
      restartPolicy: OnFailure
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}-realm-update
      volumes:
        - name: admin-credentials
          secret:
            secretName: keycloak-admin-secret
            items:
              - key: user
                path: username
              - key: password
                path: password
        - name: realm-update-scripts
          configMap:
            defaultMode: 0755
            name: {{ include "keycloak.fullname" . }}-realm-update-scripts
        - name: workdir
          emptyDir: {}
