{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sas-retrieval-agent-manager-api.serviceAccountName" . }}
  labels:
    {{- include "sas-retrieval-agent-manager-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs", "jobs/status"]
    verbs: ["create", "get", "list", "watch", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["keycloak-certs"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]

  # - apiGroups: ["", "batch", "apps"]
  #   resources: ["pods", "services", "jobs", "configmaps", "jobs/status", "pods/log", "deployments", "cronjobs"]
  #   verbs: ["create", "get", "list", "watch", "delete", "patch"]
{{- end }}