{{- $repo_base := "" -}}
{{- if ((include "testValuesPath" (list .Values "global" "image" "repo" "base")) | eq "true") -}}
  {{- $repo_base = .Values.global.image.repo.base | default (index .Values "sas-retrieval-agent-manager-app").image.repo.base -}}
{{- else -}}
  {{- $repo_base = (index .Values "sas-retrieval-agent-manager-app").image.repo.base -}}
{{- end -}}
{{- $globalEnabled := false }}
{{- if hasKey .Values "global" }}
{{- if hasKey .Values.global "ingress" }}
{{- if .Values.global.ingress.enabled }}
{{- $globalEnabled = .Values.global.ingress.enabled }}
{{- $globalEnabled = .Values.global.ingress.enabled }}
{{- end }}
{{- end }}
{{- end }}
{{- $uiPath := "" -}}
{{- if $globalEnabled }}
{{- $uiPath = regexReplaceAll "\\(.*" (first (index .Values "sas-retrieval-agent-manager-app").ingress.paths).path "" }}
{{- else }}
{{- if (len (index .Values "sas-retrieval-agent-manager-app").ingress.hosts) }}
{{- $uiPath = regexReplaceAll "\\(.*" (first (first (index .Values "sas-retrieval-agent-manager-app").ingress.hosts).paths).path "" }}
{{- end }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sas-retrieval-agent-manager-ui.fullname" . }}
  labels:
    {{- include "sas-retrieval-agent-manager-ui.labels" . | nindent 4 }}
spec:
  {{- if not (index .Values "sas-retrieval-agent-manager-app").autoscaling.enabled }}
  replicas: {{ (index .Values "sas-retrieval-agent-manager-app").replicaCount }}
  {{- end }}
  {{- with (index .Values "sas-retrieval-agent-manager-app").strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sas-retrieval-agent-manager-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with (index .Values "sas-retrieval-agent-manager-app").podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sas-retrieval-agent-manager-ui.labels" . | nindent 8 }}
        {{- with (index .Values "sas-retrieval-agent-manager-app").podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with uniq (concat ((index .Values "sas-retrieval-agent-manager-app").imagePullSecrets | default (list)) (.Values.global.imagePullSecrets | default (list))) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sas-retrieval-agent-manager-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml (index .Values "sas-retrieval-agent-manager-app").podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml (index .Values "sas-retrieval-agent-manager-app").securityContext | nindent 12 }}
          image: "{{ $repo_base }}/{{ (index .Values "sas-retrieval-agent-manager-app").image.repo.path }}:{{ (index .Values "sas-retrieval-agent-manager-app").image.tag }}"
          imagePullPolicy: {{ (index .Values "sas-retrieval-agent-manager-app").image.pullPolicy }}
          env:
            - name: LOGOUT_URL
              valueFrom:
                configMapKeyRef:
                  name: oauth-proxy-config
                  key: logoutUrl
            - name: POSTGREST_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: postgrest-configmap
                  key: service
            - name: SSL_VERIFY
              value: '{{ index .Values.global.configuration.ui "sslVerify" }}'
          ports:
            - name: http
              containerPort: {{ (index .Values "sas-retrieval-agent-manager-app").service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ $uiPath }}/health
              port: {{ (index .Values "sas-retrieval-agent-manager-app").livenessProbe.httpGet.port }}
            timeoutSeconds: {{ (index .Values "sas-retrieval-agent-manager-app").livenessProbe.timeoutSeconds }}
            periodSeconds: {{ (index .Values "sas-retrieval-agent-manager-app").livenessProbe.periodSeconds }}
            successThreshold: {{ (index .Values "sas-retrieval-agent-manager-app").livenessProbe.successThreshold }}
            failureThreshold: {{ (index .Values "sas-retrieval-agent-manager-app").livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ $uiPath }}/health
              port: {{ (index .Values "sas-retrieval-agent-manager-app").readinessProbe.httpGet.port }}
            timeoutSeconds: {{ (index .Values "sas-retrieval-agent-manager-app").readinessProbe.timeoutSeconds }}
            periodSeconds: {{ (index .Values "sas-retrieval-agent-manager-app").readinessProbe.periodSeconds }}
            successThreshold: {{ (index .Values "sas-retrieval-agent-manager-app").readinessProbe.successThreshold }}
            failureThreshold: {{ (index .Values "sas-retrieval-agent-manager-app").readinessProbe.failureThreshold }}
          resources:
            {{- toYaml (index .Values "sas-retrieval-agent-manager-app").resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: cache
            - mountPath: /var/run
              name: run
            - mountPath: /home/sas/.promptfoo
              name: promptfoo
          {{- with (index .Values "sas-retrieval-agent-manager-app").volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: promptfoo
          emptyDir: {}
      {{- with (index .Values "sas-retrieval-agent-manager-app").volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index .Values "sas-retrieval-agent-manager-app").nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index .Values "sas-retrieval-agent-manager-app").affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index .Values "sas-retrieval-agent-manager-app").tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}