apiVersion: v1
kind: Service
metadata:
  name: {{ include "sas-retrieval-agent-manager-ui.fullname" . }}
  labels:
    {{- include "sas-retrieval-agent-manager-ui.labels" . | nindent 4 }}
spec:
  type: {{ (index .Values "sas-retrieval-agent-manager-app").service.type }}
  ports:
    - port: {{ (index .Values "sas-retrieval-agent-manager-app").service.port }}
      targetPort: oauth2-proxy0
      protocol: TCP
      name: http
  selector:
    {{- include "sas-retrieval-agent-manager-ui.selectorLabels" . | nindent 4 }}