{{- if (index .Values "keycloak").serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oauth2-proxy.serviceAccountName" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
  {{- with (index .Values "keycloak").oauthProxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ (index .Values "keycloak").oauthProxy.serviceAccount.automount }}
{{- end }}