apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.oauthProxy.fullname" . | lower }}
  labels:
    {{- include "keycloak.oauthProxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.keycloak.oauthProxy.service.type }}
  ports:
    - port: {{ .Values.keycloak.oauthProxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "keycloak.oauthProxy.selectorLabels" . | nindent 4 }}