{{- if .Values.global.configuration.llmHydration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: llm-key
  labels:
    {{- include "sas-retrieval-agent-manager-db-migration.labels" . | nindent 4 }}
stringData:
  apiKey: {{ .Values.global.configuration.llmHydration.key | b64dec | quote }}
{{- end }}
