{{- if (index .Values "sas-retrieval-agent-manager-db-migration").serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sas-retrieval-agent-manager-db-migration.serviceAccountName" . }}
  labels:
    {{- include "sas-retrieval-agent-manager-db-migration.labels" . | nindent 4 }}
  {{- with (index .Values "sas-retrieval-agent-manager-db-migration").serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ (index .Values "sas-retrieval-agent-manager-db-migration").serviceAccount.automount }}
{{- end }}