apiVersion: v2
name: trust-manager
description: >
  Trust-Manager chart for SAS Retrieval Agent Manager.
  Deploys trust-manager and configures required trust bundles.
icon: https://cert-manager.io/favicons/favicon-32x32.png
type: application
version: 1.0.1
appVersion: "0.0.1"
dependencies:
  - name: trust-manager
    version: "v0.18.0"
    repository: "https://charts.jetstack.io"
