# @schema
# type: object
# required: true
# @schema
# -- Trust-Manager configuration for trust bundle management
trust-manager:
  # @schema
  # type: object
  # required: true
  # @schema
  # -- Custom Resource Definitions configuration
  crds:
    # @schema
    # type: boolean
    # default: true
    # required: true
    # @schema
    # -- Whether to install Trust-Manager CRDs
    enabled: true
