{{- if include "gpg.shouldGenerateKeys" . }}
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gpg.serviceAccountName" . }}
  labels:
    {{- include "gpg.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "gpg.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "gpg.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}