{{- if include "gpg.shouldGenerateKeys" . }}
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gpg.serviceAccountName" . }}
  labels:
    {{- include "gpg.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["gpg-private-key" ]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["gpg-public-key"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["list", "create"]
{{- end }}
{{- end }}