{{- $keycloak_repo_base := "" -}}
{{- $kubectl_repo_base := "" }}
{{- if ((include "testValuesPath" (list .Values.keycloak "global" "image" "repo" "base")) | eq "true") }}
  {{/* Images if mirrored repository is used */}}
  {{- $keycloak_repo_base = .Values.global.image.repo.base | default .Values.keycloak.image.keycloak.repo.base }}
  {{- $kubectl_repo_base = .Values.global.image.repo.base | default .Values.keycloak.image.kubectl.repo.base }}
{{- else }}
  {{/* Images if mirrored repository is not used */}}
  {{- $keycloak_repo_base = .Values.keycloak.image.keycloak.repo.base }}
  {{- $kubectl_repo_base = .Values.keycloak.image.kubectl.repo.base }}
{{ end -}}
{{- $globalEnabled := false }}
{{- if hasKey .Values "global" }}
{{- if hasKey .Values.global "ingress" }}
{{- if hasKey .Values.global.ingress "enabled" }}
{{- $globalEnabled = .Values.global.ingress.enabled }}
{{- end }}
{{- end }}
{{- end }}
{{- $keycloakPath := "" -}}
{{- if $globalEnabled }}
{{- $keycloakPath = regexReplaceAll "\\(.*" (first (index .Values "keycloak").ingress.paths).path "" }}
{{- else }}
{{- if (len (index .Values "keycloak").ingress.hosts) }}
{{- $keycloakPath = regexReplaceAll "\\(.*" (first (first (index .Values "keycloak").ingress.hosts).paths).path "" }}
{{- end }}
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keycloak.fullname" . }}-realm-update
  labels:
    ram-base-job: "true"
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  template:
    spec:
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |
              while [ $(curl -sw '%{http_code}' "http://{{ include "keycloak.fullname" . | lower }}:{{ .Values.keycloak.service.port }}{{ $keycloakPath }}/realms/master" -o /dev/null) -ne 200 ]; do
                echo "Waiting for ID provider to reach ready state...";
                sleep 15;
              done
          image: "{{ $kubectl_repo_base }}/{{ .Values.keycloak.image.kubectl.repo.path }}:{{ .Values.keycloak.image.kubectl.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.kubectl.pullPolicy }}
          name: idp-ready
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
          securityContext:
            {{- toYaml .Values.keycloak.securityContext | nindent 12 }}
      containers:
        - name: update-realm
          image: "{{ $keycloak_repo_base }}/{{ .Values.keycloak.image.keycloak.repo.path }}:{{ .Values.keycloak.image.keycloak.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.keycloak.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "keycloak.fullname" . }}-realm-update-env
                optional: false
          env:
            - name: KCADM_CFG_PATH
              value: "/workdir/kcadm.config"
          securityContext:
            {{- toYaml .Values.keycloak.securityContext | nindent 12 }}
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 50m
              memory: 128Mi
          command:
            - "/updates/apply.sh"
          volumeMounts:
            - mountPath: /admin
              name: admin-credentials
              readOnly: true
            - mountPath: /updates
              name: realm-update-scripts
            - mountPath: /workdir
              name: workdir
      restartPolicy: OnFailure
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}-realm-update
      volumes:
        - name: admin-credentials
          secret:
            secretName: keycloak-admin-secret
            items:
              - key: user
                path: username
              - key: password
                path: password
        - name: realm-update-scripts
          configMap:
            defaultMode: 0755
            name: {{ include "keycloak.fullname" . }}-realm-update-scripts
        - name: workdir
          emptyDir: {}