kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "keycloak.serviceAccountName" . }}-realm-update
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with (index .Values "keycloak").serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak.serviceAccountName" . }}-realm-update
roleRef:
  kind: Role
  name: {{ include "keycloak.serviceAccountName" . }}-realm-update
  apiGroup: rbac.authorization.k8s.io
