{{- if (index .Values "keycloak").serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak.serviceAccountName" . }}-realm-update
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with (index .Values "keycloak").serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ (index .Values "keycloak").serviceAccount.automount }}
{{- end }}
