{{- if (index .Values "sas-retrieval-agent-manager-api").serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sas-retrieval-agent-manager-api.serviceAccountName" . }}
  labels:
    {{- include "sas-retrieval-agent-manager-api.labels" . | nindent 4 }}
  {{- with (index .Values "sas-retrieval-agent-manager-api").serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "sas-retrieval-agent-manager-api.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "sas-retrieval-agent-manager-api.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}