apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgrest.fullname" . }}-admin
  labels:
    {{- include "postgrest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgrest.adminService.type }}
  ports:
    - port: {{ .Values.postgrest.adminService.port }}
      targetPort: admin
      protocol: TCP
      name: admin
    - port: {{ index .Values.global.configuration.postgrest.monitoring "admin-server-port" }}
      targetPort: admin-monitor
      protocol: TCP
      name: admin-monitor
  selector:
    {{- include "postgrest.selectorLabels" . | nindent 4 }}
