{{- $dot := . -}}
{{- $globalEnabled := false -}}
{{- $globalDomain := false -}}
{{- if hasKey .Values "global" -}}
{{- if hasKey .Values.global "ingress" -}}
{{- if .Values.global.ingress.enabled -}}
{{- $globalEnabled = .Values.global.ingress.enabled -}}
{{- $globalDomain = .Values.global.domain | default (first (index .Values "postgrest").ingress.hosts).host -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- if or (index .Values "postgrest").ingress.enabled $globalEnabled -}}
{{- $fullName := include "postgrest.fullname" . | lower -}}
{{- $svcPort := (index .Values "postgrest").service.port -}}
{{- $svcPortMonitoring := index .Values.global.configuration.postgrest.monitoring "server-port" -}}
{{- if and (index .Values "postgrest").ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey (index .Values "postgrest").ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set (index .Values "postgrest").ingress.annotations "kubernetes.io/ingress.class" (index .Values "postgrest").ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "postgrest.labels" . | nindent 4 }}
  {{- with (index .Values "postgrest").ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if $globalEnabled | default false }}
  {{- if and (.Values.global.ingress.className | default (index .Values "postgrest").ingress.className) (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.global.ingress.className | default (index .Values "postgrest").ingress.className  }}
  {{- end }}
  {{- if and ((include "testValuesPath" (list .Values "global" "ingress" "tls" "enabled")) | eq "true"  | default false) (.Values.global.ingress.tls.enabled | default false) }}
  tls:
    - hosts:
      - {{ $globalDomain }}
      {{- if (include "testValuesPath" (list .Values "ingress" "tls" "hosts")) | eq "true" }}
        {{- range (index .Values "postgrest").ingress.tls.hosts }}
          {{- if and . (ne . "") }}
      - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if ((include "testValuesPath" (list .Values "global" "ingress" "tls" "secretName")) | eq "true") }}
      secretName: {{ .Values.global.ingress.tls.secretName | default "" }}
      {{- else if ((include "testValuesPath" (list .Values "ingress" "tls" "secretName")) | eq "true") }}
      secretName: {{ (index .Values "postgrest").ingress.tls.secretName | default "" }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ $globalDomain | quote }}
      http:
        paths:
          {{- range (index .Values "postgrest").ingress.paths }}
          {{- if contains "/monitoring" .path }}
          - path: {{ .path}}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPortMonitoring }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPortMonitoring }}
              {{- end }}
          {{- else }}
          - path: {{ .path}}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
          {{- end }}
  {{- else }}
  {{- if and (index .Values "postgrest").ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ (index .Values "postgrest").ingress.className }}
  {{- end }}
  {{- if (index .Values "postgrest").ingress.tls }}
  tls:
    {{- range (index .Values "postgrest").ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range (index .Values "postgrest").ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- if contains "/monitoring" .path }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPortMonitoring }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPortMonitoring }}
              {{- end }}
          {{- else }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- if $.Values.global.configuration.swagger }}
          - path: /openapi.json
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}