kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "postgrest.serviceAccountName" . }}
  labels:
    {{- include "postgrest.labels" . | nindent 4 }}
  {{- with (index .Values "postgrest").serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "postgrest.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "postgrest.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io