{{- if (index .Values "postgrest").serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgrest.serviceAccountName" . }}
  labels:
    {{- include "postgrest.labels" . | nindent 4 }}
  {{- with (index .Values "postgrest").serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ (index .Values "postgrest").serviceAccount.automount }}
{{- end }}