apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgrest.fullname" . }}
  labels:
    {{- include "postgrest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgrest.service.type }}
  ports:
    - port: {{ .Values.postgrest.service.port }}
      targetPort: oauth2-proxy0
      protocol: TCP
      name: http
    - port: {{ index .Values.global.configuration.postgrest.monitoring "server-port" }}
      targetPort: oauth2-proxy1
      protocol: TCP
      name: http-monitor
  selector:
    {{- include "postgrest.selectorLabels" . | nindent 4 }}
