apiVersion: v1
kind: Secret
metadata:
  name: otel-db-credentials
  labels:
    {{- include "sas-retrieval-agent-manager-db-init.labels" . | nindent 4 }}
stringData:
  user: {{ .Values.global.configuration.otel.user | quote }}
  password: {{ .Values.global.configuration.otel.password | quote }}
