{{- if (index .Values "keycloak").ingress.admin.enabled }}
{{- $dot := . -}}
{{- $globalEnabled := false -}}
{{- if hasKey .Values "global" -}}
{{- if hasKey .Values.global "ingress" -}}
{{- if .Values.global.ingress.enabled -}}
{{- $globalEnabled = .Values.global.ingress.enabled -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- if or (index .Values "keycloak").ingress.enabled $globalEnabled -}}
{{- $fullName := include "keycloak.fullname" . | lower -}}
{{- $svcPort := (index .Values "keycloak").service.port -}}
{{- if and (index .Values "keycloak").ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey (index .Values "keycloak").ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set (index .Values "keycloak").ingress.annotations "kubernetes.io/ingress.class" (index .Values "keycloak").ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-admin
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    {{- with (index .Values "keycloak").ingress.admin.sourceRange }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," . | quote }}
    {{- end }}
    {{- with (index .Values "keycloak").ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if $globalEnabled | default false }}
  {{- if and (.Values.global.ingress.className | default (index .Values "keycloak").ingress.className) (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.global.ingress.className | default (index .Values "keycloak").ingress.className  }}
  {{- end }}
  {{- if and ((include "testValuesPath" (list .Values "global" "ingress" "tls" "enabled")) | eq "true"  | default false) (.Values.global.ingress.tls.enabled | default false) }}
  tls:
    - hosts:
        - {{ .Values.global.domain | quote }}
      {{- if (include "testValuesPath" (list .Values "ingress" "tls" "hosts")) | eq "true" }}
        {{- range (index .Values "keycloak").ingress.tls.hosts }}
          {{- if and . (ne . "") }}
        - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if ((include "testValuesPath" (list .Values "global" "ingress" "tls" "secretName")) | eq "true") }}
      secretName: {{ .Values.global.ingress.tls.secretName | default "" }}
      {{- else if ((include "testValuesPath" (list .Values "ingress" "tls" "secretName")) | eq "true") }}
      secretName: {{ (index .Values "keycloak").ingress.tls.secretName | default "" }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.global.domain | quote }}
      http:
        paths:
          - path: {{ (index .Values "keycloak").ingress.admin.path }}
            {{- if and (index .Values "keycloak").ingress.admin.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ (index .Values "keycloak").ingress.admin.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
  {{- else }}
  {{- if and (index .Values "keycloak").ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ (index .Values "keycloak").ingress.className }}
  {{- end }}
  {{- if (index .Values "keycloak").ingress.tls }}
  tls:
    {{- range (index .Values "keycloak").ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ (index .Values "keycloak").ingress.admin.host | quote }}
      http:
        paths:
          - path: {{ (index .Values "keycloak").ingress.admin.path }}
            {{- if and (index .Values "keycloak").ingress.admin.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ (index .Values "keycloak").ingress.admin.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
  {{- end }}
{{- end }}
{{- end}}