apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "keycloak.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 10%
  selector:
    matchExpressions:
    - key: batch.kubernetes.io/job-name
      operator: DoesNotExist
    matchLabels:
      app.kubernetes.io/name: keycloak
