apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-webhook-issuer
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  ca:
    secretName: linkerd-webhook-issuer