{{- if and (index .Values "filebrowser").enabled (index .Values "filebrowser").serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "storage.serviceAccountName" . }}
  labels:
    {{- include "storage.labels" . | nindent 4 }}
  {{- with (index .Values "filebrowser").serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}