apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  sources:
  - secret:
      name: linkerd-trust-anchor
      key: "ca.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
