apiVersion: v1
kind: ConfigMap
metadata:
  name: db-monitoring
  namespace: retagentmgr
  labels:
    {{- include "sas-retrieval-agent-manager-db-init.labels" . | nindent 4 }}
data:
  db: {{ .Values.global.configuration.postgrest.db | quote }}
  schema: {{ .Values.global.configuration.postgrest.schema | quote }}
