{{- if (index .Values "sas-retrieval-agent-manager-db-init").serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sas-retrieval-agent-manager-db-init.serviceAccountName" . }}
  labels:
    {{- include "sas-retrieval-agent-manager-db-init.labels" . | nindent 4 }}
  {{- with (index .Values "sas-retrieval-agent-manager-db-init").serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["admin-db-credentials"]
    verbs: ["get", "patch"]
{{- end }}