{{- if (index .Values "sas-retrieval-agent-manager-db-init").serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sas-retrieval-agent-manager-db-init.serviceAccountName" . }}
  labels:
    {{- include "sas-retrieval-agent-manager-db-init.labels" . | nindent 4 }}
  {{- with (index .Values "sas-retrieval-agent-manager-db-init").serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ (index .Values "sas-retrieval-agent-manager-db-init").serviceAccount.automount }}
{{- end }}