{{- $dot := . -}}
{{- $globalEnabled := false -}}
{{- if hasKey .Values "global" -}}
{{- if hasKey .Values.global "ingress" -}}
{{- if .Values.global.ingress.enabled -}}
{{- $globalEnabled = .Values.global.ingress.enabled -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- if (index .Values "postgrest").swagger.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgrest.swagger.fullname" . }}
  labels:
    {{- include "postgrest.swagger.labels" . | nindent 4 }}
spec:
  replicas: {{ (index .Values "postgrest").swagger.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgrest.swagger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with (index .Values "postgrest").swagger.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgrest.swagger.labels" . | nindent 8 }}
        {{- with (index .Values "postgrest").swagger.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with uniq (concat ((index .Values "postgrest").imagePullSecrets | default (list)) (.Values.global.imagePullSecrets | default (list))) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml (index .Values "postgrest").swagger.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}-swagger
          securityContext:
            {{- toYaml (index .Values "postgrest").swagger.securityContext | nindent 12 }}
          image: "{{ (index .Values "postgrest").swagger.image.repo.base }}/{{ (index .Values "postgrest").swagger.image.repo.path }}:{{ (index .Values "postgrest").swagger.image.tag }}"
          imagePullPolicy: {{ (index .Values "postgrest").swagger.image.pullPolicy }}
          env:
            - name: VALIDATOR_URL
              value: "none"
            - name: URL
              value: {{ if $globalEnabled -}}
                        "https://{{ .Values.global.domain }}/postgrest"
                     {{- else -}}
                        "https://{{ with (first (index .Values "postgrest").ingress.hosts) }}{{ .host }}{{ with (first .paths) }}/{{ regexReplaceAll "\\(.*" .path "" }}{{ end }}{{ end }}"
                     {{- end }}
            - name: URLS
              value: {{ if $globalEnabled -}}
                        '[{"name":"PostgREST","url":"https://{{ .Values.global.domain }}/postgrest"}]'
                     {{- else -}}
                        '[{"name":"PostgREST","url":"https://{{ with (first (index .Values "postgrest").ingress.hosts) }}{{ .host }}{{ with (first .paths) }}/{{ regexReplaceAll "\\(.*" .path "" }}{{ end }}{{ end }}"}]'
                     {{- end }}
            - name: WITH_CREDENTIALS
              value: "true"
            - name: OAUTH2_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret
                  key: oauthUrl
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret
                  key: sv-client-id
            - name: OAUTH_REALM
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret
                  key: realm
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml (index .Values "postgrest").swagger.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml (index .Values "postgrest").swagger.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml (index .Values "postgrest").swagger.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: "/etc/nginx/conf.d/"
            - name: workdir
              mountPath: "/tmp"
          {{- with (index .Values "postgrest").swagger.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: nginx-conf
          emptyDir: {}
        - name: workdir
          emptyDir: {}
      {{- with (index .Values "postgrest").swagger.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index .Values "postgrest").swagger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index .Values "postgrest").swagger.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index .Values "postgrest").swagger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}