{{- if .Values.postgrest.swagger.enabled }}
{{- $swaggerName := include "postgrest.swagger.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgrest.swagger.fullname" . }}
  labels:
    {{- include "postgrest.swagger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgrest.swagger.service.type }}
  ports:
    - port: {{ .Values.postgrest.swagger.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "postgrest.swagger.selectorLabels" . | nindent 4 }}
{{- end }}