{{- if (index .Values "postgrest").swagger.enabled -}}
{{- if (index .Values "postgrest").swagger.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgrest.swagger.serviceAccountName" . }}
  labels:
    {{- include "postgrest.swagger.labels" . | nindent 4 }}
  {{- with (index .Values "postgrest").swagger.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ (index .Values "postgrest").swagger.serviceAccount.automount }}
{{- end }}
{{- end }}